### ISSUE TITLE
Prediction models and hyperparameters

### ISSUE THREAD

**Issue by Aminsheykh98** [JingweiZuo/PurpleAirSF#1]
Hi, Thank you for your work. This dataset is incredibly useful and truly a blessing for me. and I believe it will help air quality forecasting research or any other related research areas a lot.
In your paper, you constructed an initial performance benchmark using LSTM and GWN. Could you please share the hyperparameters (or code) you used for training these models?

**Comment by JingweiZuo** [comment]
Dear Amin, 

I appreciate your interest in our research.

To achieve our results, we utilized a single-layer LSTM with a hidden dimension of 12 multiplied by the number of nodes (nbr_nodes). This was followed by a fully connected layer to generate the forecast in the desired dimensions. While this configuration worked for our purpose, I believe there's potential for optimization based on specific needs.

As for the Graph WaveNet (GWN) implementation, we relied on the official code. You can access and review it at the following GitHub repository: https://github.com/nnzhan/Graph-WaveNet.

I trust this information will be useful to you. Please don't hesitate to reach out if you have further questions or require additional clarification.

Warm regards,
Jingwei Zuo
