### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by fireppGo** [JingweiZuo/PurpleAirSF#2]
1. How to understand pm2.5_alt, pm2.5_cf_1,pm2.5_atm.
2. If I want to use normal pm2.5, which one should I use.

Thanks.

**Comment by JingweiZuo** [comment]
Hello,

Thank you for your interest in this dataset. 

You can find the detailed description of the three pm2.5 measures [here](https://community.purpleair.com/t/what-is-the-difference-between-cf-1-atm-and-alt/6442). 

Those are three different ways to measure pm2.5. _pm2.5_alt_ is more accurate than the two others, which reflects the real pm2.5 situation. You can pick that one as the forecasting target if needed.

Hope this helps,

Kind regards.
Jingwei
