### ISSUE TITLE
Inquiry about Timestamps in This Dataset

### ISSUE THREAD

**Issue by HowardZorn** [JingweiZuo/PurpleAirSF#3]
I'm currently diving into your dataset. It's been incredibly helpful for my project. However, I'm curious about the accurate timestamps in the dataset. Could you provide some more details about how timestamps are recorded?

Thanks a bunch for your hard work in putting together and sharing this dataset!

Cheers,
Fw[a]rd.

**Comment by JingweiZuo** [comment]
Thank you for your interest in the PupleAirSF dataset. 

After the careful preprocessing, we took the Air Quality data of San Francisco between 2021-10-01 and 2023-05-15. The timestamps depend on the sampling rates, i.e., time interval between two records can be 10 mins, 1 hour or 6 hours.

Feel free to let me know if you have further questions.
Best,

**Comment by HowardZorn** [comment]
> Thank you for your interest in the PupleAirSF dataset.

Thank you for such a prompt response. The data were collected between October 1, 2021, and May 15, 2023, as indicated in your paper. I have observed that there are 81,825 timestamps in PurpleAirSF-10M, 13,633 in PurpleAirSF-1H, and 2,281 in PurpleAirSF-6H. Upon preprocessing these timestamps, I obtained the following results:

```
In [1]: from datetime import datetime, timedelta

In [2]: print(datetime(2021, 10, 1, 0, 0, 0) + timedelta(minutes=10) * (81825 - 1))
2023-04-22 05:20:00

In [3]: print(datetime(2021, 10, 1, 0, 0, 0) + timedelta(hours=1) * (13633 - 1))
2023-04-22 00:00:00

In [4]: print(datetime(2021, 10, 1, 0, 0, 0) + timedelta(hours=6) * (2281 - 1))
2023-04-24 00:00:00
```

So, is it the case that these data are missing, or was these data not collected as of May 15, 2023?

Best,
Fw[a]rd.

**Comment by JingweiZuo** [comment]
> > Thank you for your interest in the PupleAirSF dataset.
> 
> Thank you for such a prompt response. The data were collected between October 1, 2021, and May 15, 2023, as indicated in your paper. I have observed that there are 81,825 timestamps in PurpleAirSF-10M, 13,633 in PurpleAirSF-1H, and 2,281 in PurpleAirSF-6H. Upon preprocessing these timestamps, I obtained the following results:
> 
> ```
> In [1]: from datetime import datetime, timedelta
> 
> In [2]: print(datetime(2021, 10, 1, 0, 0, 0) + timedelta(minutes=10) * (81825 - 1))
> 2023-04-22 05:20:00
> 
> In [3]: print(datetime(2021, 10, 1, 0, 0, 0) + timedelta(hours=1) * (13633 - 1))
> 2023-04-22 00:00:00
> 
> In [4]: print(datetime(2021, 10, 1, 0, 0, 0) + timedelta(hours=6) * (2281 - 1))
> 2023-04-24 00:00:00
> ```
> 
> So, is it the case that these data are missing, or was these data not collected as of May 15, 2023?
> 
> Best, Fw[a]rd.

Hi Fw[a]rd,

Thanks for the details remarks. It should not be related to the missing values. We did not remove any missing values/intervals in this one-half-year period, as it will either introduce human interference for the raw information or break the continuity of the sequence. Instead, all missing values are represented by zeros in the sequence (a small portion).

You are right, the ending date is not exactly May 15, 2023, and are not exactly the same for the three sampling rates. However, they should be starting all from October 1, 2021.

I hope this helps,
Best,
Jingwei

**Comment by HowardZorn** [comment]
Thank you for your reply. Actually, your datasets have helped me a lot. Thanks again for your hard work in putting together and sharing this dataset!

**Comment by JingweiZuo** [comment]
> Thank you for your reply. Actually, your datasets have helped me a lot. Thanks again for your hard work in putting together and sharing this dataset!

Very glad to have your feedback. Enjoy playing with the dataset :)
