### ISSUE TITLE
Links for 10M and 1H datasets

### ISSUE THREAD

**Issue by patel-zeel** [JingweiZuo/PurpleAirSF#4]
Hi, thanks for your work in democratizing air quality data. I could find the 6H data in the drive link but could not find 1H and 10M datasets. Can you please help with that?

**Comment by JingweiZuo** [comment]
Hi, 

Thank you for the reminder. They were accidentally deleted by Google Drive due to space limit. Now they have been recovered. 

Best,
Jingwei

**Comment by patel-zeel** [comment]
Thank you for your prompt response and resolution!
